# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
# 
development: 
    adapter: postgresql
    database: combat_creator_2_development
    encoding: unicode
    pool: 5
    timeout: 5000

test:
    adapter: postgresql
    encoding: unicode
    database: combat_creator_2_test
    pool: 5
    timeout: 5000